/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class com_convert_mymp3convert_MyTest */

#pragma once
#include <jni.h>
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_convert_mymp3convert_MyTest
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_convert_mymp3convert_MyTest_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif

