/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_convert_mymp3convert_Mp3ConvertUtil */

#ifndef _Included_com_convert_mymp3convert_Mp3ConvertUtil
#define _Included_com_convert_mymp3convert_Mp3ConvertUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_convert_mymp3convert_Mp3ConvertUtil
 * Method:    hello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_convert_mymp3convert_Mp3ConvertUtil_hello
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_convert_mymp3convert_Mp3ConvertUtil
 * Method:    getLameVer
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_convert_mymp3convert_Mp3ConvertUtil_getLameVer
  (JNIEnv *, jclass);

/*
 * Class:     com_convert_mymp3convert_Mp3ConvertUtil
 * Method:    convertmp3
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_convert_mymp3convert_Mp3ConvertUtil_convertmp3
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
